import { ROOT_OP_NAMES, GQL_NAMED_TYPES } from '../types';

export const DELIM = '::';

export const DEF_GEN_PATTERN = `\\n(?=\\s*(?=${GQL_NAMED_TYPES.OBJECT_TYPE}|${GQL_NAMED_TYPES.INPUT}|${GQL_NAMED_TYPES.ENUM}|${GQL_NAMED_TYPES.INTERFACE}|${GQL_NAMED_TYPES.UNION}))`;

export const QUERY_OP_PATTERN = `\\b${ROOT_OP_NAMES.QUERY}(?=\\s*{)`;

export const MUTATION_OP_PATTERN = `\\b${ROOT_OP_NAMES.MUTATION}(?=\\s*{)`;

export const SUBSCRIPTION_OP_PATTERN = `\\b${ROOT_OP_NAMES.SUBSCRIPTION}(?=\\s*{)`;

export const ROOT_OP_PATTERN = `${QUERY_OP_PATTERN}|${MUTATION_OP_PATTERN}|${SUBSCRIPTION_OP_PATTERN}`;

export const CHARAC_CLEAN_PATTERN = `\\s+|${GQL_NAMED_TYPES.OBJECT_TYPE}|{|}`;

export const EMPTY_STRING_PATTERN = `^$`;